furiko-io/furiko

.github/workflows/ci.yml
Adds a GitHub action for automated CI, including:
1. Lint Go code using `golangci-lint`
2. Codegen linter to ensure that all codegen is up-to-date in a single change
3. Ensure that license headers are correct for Go code using [lsm-dev/license-header-checker](https://github.com/lsm-dev/license-header-checker)
4. Test Go code and upload coverage to Codecov
=> chore: Add GitHub Action for CI

.dockerignore, .github/workflows/ci.yml, .gitignore, Makefile
In Go 1.18, using `go get` to install go binaries is no longer supported, which breaks the `go-get-tool` step in the Makefile. This was originally taken from Kubebuilder, and it looks like the new recommended approach is to simply use `go install`: https://github.com/kubernetes-sigs/kubebuilder/pull/2486
This PR fixes all build dependencies to use the new method, and also adds a new Makefile target `yaml`, which generates all YAML configurations into `dist/`. Additional clean up and comments are also added.
=> chore: Fix Makefile to support Go 1.18

apis/execution/v1alpha1/job_types.go, config/crd/bases/execution.furiko.io_jobs.yaml
Fixes CRD description for DeletedStatus field.
=> typo: Fix DeletedStatus description

cmd/execution-controller/main.go, pkg/execution/controllers/croncontroller/control.go, pkg/execution/controllers/croncontroller/control_test.go, pkg/execution/controllers/croncontroller/controller.go, pkg/execution/controllers/croncontroller/reconciler.go, pkg/execution/controllers/croncontroller/reconciler_test.go, pkg/execution/controllers/croncontroller/schedule_test.go, pkg/execution/controllers/croncontroller/util.go, pkg/execution/controllers/croncontroller/util_test.go, pkg/execution/controllers/jobqueuecontroller/reconciler_perjobconfig.go, pkg/execution/stores/activejobstore/store.go, pkg/execution/stores/activejobstore/store_test.go, pkg/runtime/controllercontext/context_stores.go, pkg/runtime/testing/concurrency.go, pkg/utils/testutils/uid.go, pkg/utils/testutils/uid_test.go
Pending #27 to be merged, since we are using some dependencies from that branch.
This PR adds further tests for CronController, and also refactors some of the scaffold to be more suitable for dependency injection.
=> feat: Add CronController tests

.goreleaser.yaml, Makefile, config/default/kustomization.yaml, hack/generate-kustomization.sh, hack/release-snapshot.sh
Adds a Makefile target to deploy snapshot into K8s cluster using `make deploy`.
Additional changes:
1. Moved `kustomize edit` logic into helper `generate-kustomization.sh` script, and updated the logic to support generating a brand-new `kustomization.yaml` which avoids clobbering the main `config/default` configuration path.
2. Clean up some accidental changes.
3. Also push `snapshot` Docker image tag, which always points to the latest snapshot image tag.
=> chore: Add Makefile target to deploy snapshot

DEVELOPMENT.md, Makefile
Adds more documentation in `DEVELOPMENT.md` to explain `make deploy`.
Also updates the `make deploy` step to support custom `IMAGE_TAG`.
=> chore: Update development docs for make deploy

.github/workflows/ci.yml
CI runs may be slow because the `go-test` job waits for other jobs like `generate-lint`. Actually it is not needed and we can parallelize them.
=> chore(ci): Parallelize lint and test stages

Makefile, apis/config/v1alpha1/configurationname_types.go, config/execution/dynamic/config.yaml, hack/run-fmt.sh, pkg/config/defaults.go, pkg/execution/controllers/croncontroller/cron_worker.go, pkg/execution/controllers/croncontroller/schedule.go, pkg/execution/controllers/croncontroller/schedule_test.go, pkg/execution/controllers/jobcontroller/controller_test.go, pkg/execution/controllers/jobcontroller/reconciler.go, pkg/execution/controllers/jobcontroller/reconciler_test.go, pkg/execution/mutation/mutation.go, pkg/execution/mutation/mutation_test.go, pkg/execution/validation/validation.go, pkg/runtime/configloader/defaults_loader.go, pkg/runtime/controllercontext/context_configs.go
Updates config names in the code, as well as rename ConfigMap file names. List of changes are below.
- `execution-job` -> `jobs`
- `execution-cron` -> `cron`
With this, we can just specify the short name in the ConfigMap itself, like so:
```yaml
apiVersion: v1
kind: ConfigMap
data:
_readme: |
cron: |
apiVersion: config.furiko.io/v1alpha1
kind: CronExecutionConfig
cronFormat: "standard"
cronHashNames: true
cronHashSecondsByDefault: false
cronHashFields: true
defaultTimezone: "UTC"
maxMissedSchedules: 5
maxDowntimeThresholdSeconds: 300
jobs: |
apiVersion: config.furiko.io/v1alpha1
kind: JobExecutionConfig
defaultTTLSecondsAfterFinished: 3600
defaultPendingTimeoutSeconds: 900
deleteKillingTasksTimeoutSeconds: 180
forceDeleteKillingTasksTimeoutSeconds: 120
```
=> refactor(config): Update dynamic config type names

pkg/execution/variablecontext/provider.go
Adds two new context variables:
- `jobconfig.uid`: The UID of the JobConfig.
- `job.uid`: The UID of the Job.
UIDs are guaranteed to be unique across all resources in the cluster. Ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids
=> feat(variablecontext): Add jobconfig.uid and job.uid context variables

.github/workflows/ci.yml, config/crd/bases/execution.furiko.io_jobconfigs.yaml, config/crd/bases/execution.furiko.io_jobs.yaml
Catches missing `make manifests` step in `generate-lint` CI step.
=> chore(ci): Also run make manifests for generate-lint step

pkg/execution/controllers/jobqueuecontroller/control.go, pkg/execution/controllers/jobqueuecontroller/controller.go, pkg/execution/controllers/jobqueuecontroller/reconciler_independent.go, pkg/execution/controllers/jobqueuecontroller/reconciler_independent_test.go, pkg/execution/controllers/jobqueuecontroller/reconciler_perjobconfig_test.go, pkg/execution/controllers/jobqueuecontroller/reconciler_test.go, pkg/runtime/controllercontext/mock/context.go, pkg/runtime/controllercontext/mock/context_stores.go
=> fix(execution): Handle IndependentReconciler bugs in JobQueueController, add tests

pkg/execution/controllers/jobcontroller/controller.go, pkg/execution/controllers/jobcontroller/reconciler_test.go, pkg/execution/controllers/jobqueuecontroller/controller.go, pkg/execution/controllers/jobqueuecontroller/reconciler_independent_test.go, pkg/execution/controllers/jobqueuecontroller/reconciler_perjobconfig_test.go, pkg/execution/controllers/jobqueuecontroller/reconciler_test.go, pkg/runtime/testing/action.go, pkg/runtime/testing/reconciler.go
Extract out a common `ReconcilerTest` for setting up and executing reconciler tests.
=> chore(refactor): Use standard reconciler test framework

pkg/runtime/httphandler/webhooks.go, pkg/runtime/httphandler/webhooks_test.go
Partially implements #5 and partially fixes #59.
- Adds panic recovery for webhook handlers.
- Always return a JSON-encoded AdmissionReview response for all errors, including recovered panics.
- Add tests.
=> fix(runtime): Implement panic recovery for webhook handlers

pkg/execution/mutation/mutation.go, pkg/execution/mutation/mutation_test.go, pkg/execution/mutation/patcher_jobconfigs.go, pkg/execution/mutation/patcher_jobs.go, pkg/execution/mutation/patcher_jobs_test.go, pkg/execution/webhooks/jobconfigmutatingwebhook/webhook.go, pkg/execution/webhooks/jobmutatingwebhook/webhook.go
Fixes #59.
- Extract JobPatcher and JobConfigPatcher from Mutator. There are many hidden assumptions in the `MutateX` methods, as we have seen that not only does it make the tests brittle, it also does not fully catch edge cases that may fall through the cracks.
- The `Patcher` types will simply just compose multiple `MutateX` methods in the desired order, and we will write tests based on the Operation and objects to be patched.
- Other fixes:
- PodTemplateSpec should only add RestartPolicy on Job creates/updates, not JobConfig.
- Handle nil for JobTemplate to add MaxAttempts.
=> fix(webhook): Handle nil in mutation webhooks

pkg/cli/cmd/cmd_run_test.go, pkg/cli/console/console.go, pkg/cli/streams/streams.go, pkg/runtime/testing/command.go
The `github.com/hinshun/vt10x` package does not support Windows:
```
../../../../pkg/mod/github.com/hinshun/vt10x@v0.0.0-20220119200601-820417d04eec/vt_other.go:26:8: t.cur.attr undefined (type Cursor has no field or method attr, but does have Attr)
../../../../pkg/mod/github.com/hinshun/vt10x@v0.0.0-20220119200601-820417d04eec/vt_other.go:27:8: t.cur.attr undefined (type Cursor has no field or method attr, but does have Attr)
```
Since we only use it for unit tests, we should chuck it into its own package so that it does not need to be imported when building the CLI.
=> chore: Move console to separate package

.goreleaser.yaml
Relates to #67.
Adds a goreleaser step to release CLI binaries via GitHub releases.
=> chore: Add goreleaser for CLI

pkg/cli/cmd/cmd.go, pkg/cli/cmd/cmd_get_job.go, pkg/cli/cmd/cmd_get_jobconfig.go, pkg/cli/cmd/cmd_kill.go, pkg/cli/cmd/cmd_kill_test.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/cmd/cmd_run.go, pkg/cli/cmd/cmd_run_test.go, pkg/cli/formatter/time.go, pkg/runtime/testing/command.go, pkg/runtime/testing/reconciler.go
=> feat(cli): Add kill subcommand

.dockerignore, Makefile, apis/config/v1alpha1/dynamicconfig_types.go, apis/config/v1alpha1/zz_generated.deepcopy.go, apis/execution/v1alpha1/job_types.go, config/execution/dynamic/config.yaml, hack/build-images.sh, pkg/config/defaults.go, pkg/execution/controllers/jobcontroller/controller_test.go, pkg/execution/controllers/jobcontroller/reconciler.go, pkg/execution/controllers/jobcontroller/reconciler_test.go, pkg/execution/taskexecutor/podtaskexecutor/labels.go, pkg/execution/taskexecutor/podtaskexecutor/pod_task.go, pkg/execution/taskexecutor/podtaskexecutor/pod_task_test.go, pkg/execution/taskexecutor/podtaskexecutor/pod_test.go, pkg/execution/tasks/interfaces.go, pkg/execution/util/job/condition.go, pkg/execution/util/job/condition_test.go, pkg/execution/util/job/phase.go, pkg/execution/util/job/task_test.go, pkg/execution/util/job/timeout.go, pkg/runtime/configloader/defaults_loader_test.go, pkg/utils/ktime/time.go
Closes #64.
Avoids using `activeDeadlineSeconds` to kill tasks, instead it will use API deletion instead, which supports graceful termination.
=> feat(execution): Avoid using activeDeadlineSeconds to kill tasks

apis/execution/v1alpha1/job_types.go, config/crd/bases/execution.furiko.io_jobs.yaml, pkg/execution/util/job/task_status.go, pkg/execution/util/job/task_status_test.go
Adds a new field `status.runningTasks`, which summarizes the total number of tasks that are running for the Job.
=> feat(api): Add status.runningTasks

pkg/execution/mutation/mutation.go, pkg/execution/mutation/mutation_test.go
Trying to apply the following YAML results in not being able to save:
```yaml
apiVersion: execution.furiko.io/v1alpha1
kind: JobConfig
metadata:
name: jobconfig-parallel-sleep
spec:
concurrency:
policy: Forbid
schedule:
cron:
expression: "H/15 * * * *"
timezone: Asia/Singapore
disabled: false
template:
spec:
parallelism:
withKeys:
- "30"
- "60"
- "120"
taskTemplate:
pod:
spec:
containers:
- name: job-container
args:
- bash
- -c
- "echo Sleeping for ${task.index_key}; sleep ${task.index_key}"
image: bash
```
The following error is displayed:
```
$ k apply -f jobconfig-parallel-sleep.yaml
The JobConfig "jobconfig-parallel-sleep" is invalid: spec.template.spec.parallelism.completionStrategy: Required value
```
By right, we should also add default values for JobTemplate in JobConfigSpec. The …
=> fix(webhook): Add default values for parallelism.completionStrategy

pkg/cli/cmd/cmd.go, pkg/cli/cmd/cmd_disable.go, pkg/cli/cmd/cmd_disable_test.go, pkg/cli/cmd/cmd_enable.go, pkg/cli/cmd/cmd_enable_test.go, pkg/cli/cmd/cmd_get_jobconfig_test.go
Adds two new subcommands:
```
Usage:
furiko [command]
Available Commands:
...
disable     Disable automatic scheduling for a JobConfig.
enable      Enable automatic scheduling for a JobConfig.
...
```
Detailed subcommand help:
```
Disables automatic scheduling for a JobConfig.
If the specified JobConfig does not have a schedule, then an error will be thrown.
If the specified JobConfig is already disabled, then this is a no-op.
Usage:
furiko disable [flags]
Examples:
furiko disable send-weekly-report
```
```
Enables automatic scheduling for a JobConfig.
If the specified JobConfig does not have a schedule, then an error will be thrown.
If the specified JobConfig is already enabled, then this is a no-op.
Usage:
furiko enable [flags]
Examples:
furiko enable send-weekly-report
```
=> feat(cli): Add enable/disable subcommands

pkg/cli/cmd/cmd_disable_test.go, pkg/cli/cmd/cmd_enable_test.go, pkg/cli/cmd/cmd_get_job_test.go, pkg/cli/cmd/cmd_get_jobconfig_test.go, pkg/cli/cmd/cmd_kill_test.go, pkg/cli/cmd/cmd_run_test.go, pkg/execution/util/parallel/indexes_test.go, pkg/execution/util/parallel/status_test.go, pkg/execution/util/schedule/schedule_test.go, pkg/runtime/controllermanager/controller_test.go, pkg/runtime/testing/command.go, pkg/utils/testutils/assert.go
Moves several error assertion functions out of `runtime/testing` into `testutils`.
=> refactor(testutils): Move error assertion functions out of runtime/testing

.golangci.yml, apis/execution/v1alpha1/job_types.go, apis/execution/v1alpha1/jobconfig_types.go, pkg/execution/mutation/mutation.go, pkg/execution/mutation/mutation_test.go, pkg/execution/validation/validation.go, pkg/execution/validation/validation_test.go, pkg/execution/webhooks/jobconfigvalidatingwebhook/webhook.go
Disables the `lll` linter. In my experience, this linter provides little value and often gets in the way especially with long function signatures or function call chains.
=> chore(lint): Remove lll from list of linters

.golangci.yml, pkg/cli/cmd/common.go, pkg/cli/prompt/prompt.go, pkg/cli/prompt/prompt_test.go, pkg/cli/prompt/validator.go
Fixes several CLI issues for `furiko run`.
1. Support AllowCustom for `Select` options by using `survey.Input` in place of `survey.Select`
[![asciicast](https://asciinema.org/a/fZy4k92gswkbSXzAAq0UcodYZ.svg)](https://asciinema.org/a/fZy4k92gswkbSXzAAq0UcodYZ)
- Currently can't add support for `Multi` options as well, because there isn't a good equivalent way
- The UX is also not perfect, perhaps this can be better fulfilled by https://github.com/go-survey/survey/issues/339
2. Fixes a validation bug where `Select` options could not be selected when `required` is `true`.
3. Adds unit tests.
=> fix(cli): Support AllowCustom and fix validation for select

hack/run-fmt.sh, pkg/cli/cmd/common.go, pkg/runtime/testing/fixture.go, pkg/runtime/testing/reconciler.go
1. Fixes comment formatting that gets messed up on `make fmt`
2. Fixes test flakiness when run locally
=> chore: Fix fmt and test flakes

Makefile, apis/execution/v1alpha1/jobconfig_types.go, pkg/cli/cmd/cmd.go, pkg/cli/cmd/cmd_disable.go, pkg/cli/cmd/cmd_enable.go, pkg/cli/cmd/cmd_get.go, pkg/cli/cmd/cmd_get_job.go, pkg/cli/cmd/cmd_get_jobconfig.go, pkg/cli/cmd/cmd_kill.go, pkg/cli/cmd/cmd_list.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_run.go, pkg/cli/cmd/common.go, pkg/cli/cmd/completion.go, pkg/cli/cmd/completion_helper.go, pkg/cli/cmd/completion_helper_test.go
Supports auto-completion of arguments and flags for all commands:
- `-n/--namespace`: Autocompletes based on list of namespaces.
- `-o/--output`: Autocompletes list of output formats.
- Autocompletes Job/JobConfig names.
_Side note: The above GIF was generated with https://github.com/charmbracelet/vhs_
=> feat(cli): Implement completion for flags and arguments

apis/execution/v1alpha1/jobconfig_types.go, config/crd/bases/execution.furiko.io_jobconfigs.yaml
Fixes incorrect printer column name for JobConfig's `lastScheduled`.
=> chore(apis): Fix additionalPrinterColumn name for lastScheduled

Makefile, hack/run-fmt.sh, pkg/execution/controllers/croncontroller/cron_worker.go
Switches to use https://github.com/incu6us/goimports-reviser to format and group imports instead. This enforces a stricter code formatting style.
=> chore(dev): Use goimports-reviser instead to group imports

pkg/cli/cmd/cmd_get_jobconfig_test.go, pkg/cli/cmd/cmd_list_job_test.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/cmd/cmd_list_jobconfig_test.go, pkg/cli/formatter/time.go
Aligns with the output from `kubectl`.
=> feat(cli): Display LastExecuted in furiko list jobconfigs

examples/jobconfigs/10-example-jobconfig.yaml, examples/jobconfigs/20-cron-schedule.yaml, examples/jobconfigs/21-hash-cron-expression.yaml, examples/jobconfigs/30-context-variables.yaml, examples/jobconfigs/31-job-options--adhoc-refund-customer-payments.yaml, examples/jobconfigs/90-full-configuration.yaml, examples/jobs/10-adhoc-job-from-config.yaml, examples/jobs/11-adhoc-job-with-options.yaml, examples/jobs/12-adhoc-future-job.yaml, examples/jobs/90-full-independent-job.yaml
Adds several example Job and JobConfig YAMLs. This will be useful for new users to Furiko, as it introduces several features and concepts in Furiko while allowing the user to easily apply them to their own clusters to test it out.
=> feat(docs): Add runnable and explainable examples

pkg/cli/cmd/cmd_list.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_list_job_test.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/cmd/cmd_list_jobconfig_test.go, pkg/cli/cmd/common.go, pkg/cli/printer/table.go, pkg/runtime/testing/command.go
Supports the `--no-headers` flag for all `list` subcommands.
=> feat(cli): Support --no-headers flag

go.mod, pkg/cli/cmd/cmd_get.go, pkg/cli/cmd/cmd_get_job.go, pkg/cli/cmd/cmd_get_jobconfig.go, pkg/cli/cmd/cmd_list.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_list_job_test.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/cmd/cmd_list_jobconfig_test.go, pkg/cli/cmd/cmd_run_test.go, pkg/cli/cmd/common.go, pkg/cli/cmd/watch.go, pkg/cli/printer/printer.go, pkg/cli/printer/printer_test.go, pkg/cli/printer/table.go, pkg/runtime/testing/command.go, pkg/runtime/testing/reconciler.go
1. Implements `--watch` for `list` subcommands.
2. Refactor flag initialization for subcommands.
3. Re-implement TablePrinter using github.com/liggitt/tabwriter.
4. Change YAML and JSON output for lists from `metav1.List` to individual documents/objects.
=> feat(cli): Implement --watch flag

.codecov.yml
Excludes Go files generated by controller-gen and generate-groups.
=> chore(ci): Exclude generated files from CodeCov

apis/execution/v1alpha1/jobconfig_types.go, pkg/cli/cmd/cmd_run.go, pkg/cli/cmd/cmd_run_test.go, pkg/cli/cmd/common.go, pkg/execution/validation/validation.go
Added several quality-of-life improvements for flags for `furiko run`.
1. Add `--after` shorthand flag for `--at`.
2. Add `--enqueue` shorthand flag for `--concurrency-policy=Enqueue`.
3. Add `--generate-name` flag.
4. Add `--option-values` flag.
5. Validate `--concurrency-policy` flag.
6. Update usage examples for `furiko run`.
7. Fixes small typo in `--no-interactive` flag's help.
=> feat(cli): Add CLI enhancements for furiko run command

pkg/cli/cmd/cmd_get_job_test.go, pkg/cli/cmd/cmd_get_jobconfig_test.go, pkg/cli/cmd/cmd_kill.go, pkg/cli/cmd/cmd_kill_test.go, pkg/cli/cmd/cmd_run.go, pkg/cli/cmd/cmd_run_test.go
1. Standardize to use `Complete()`, `Validate()`, `Run()` functions.
2. Add validation for time in the past in `--after` and `--at` for the `run` command.
3. Standardize `-t` and `-p` shorthand flags from `kill` to `run` also.
4. Fix some typos in error messages.
=> chore(cli): Improve validation for kill and run commands

apis/execution/v1alpha1/job_types.go, config/crd/bases/execution.furiko.io_jobs.yaml, pkg/cli/cmd/cmd_get_job.go, pkg/cli/cmd/cmd_get_job_test.go, pkg/cli/cmd/cmd_get_jobconfig_test.go, pkg/execution/controllers/jobcontroller/controller_test.go, pkg/execution/controllers/jobcontroller/reconciler.go, pkg/execution/controllers/jobcontroller/util.go
Introduces `JobState`, which is a simplified version of `JobPhase`.
The value of JobState is intended to match the non-nil value in JobCondition exactly, and will be written to JobStatus for greater clarity and convenience.
=> feat(execution): Add JobState field to JobStatus

go.mod, go.sum, pkg/cli/cmd/cmd_get_job_test.go, pkg/cli/cmd/cmd_get_jobconfig_test.go, pkg/cli/cmd/cmd_list.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_list_job_test.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/cmd/cmd_list_jobconfig_test.go, pkg/cli/cmd/watch.go, pkg/execution/util/jobconfig/state.go, pkg/runtime/testing/command.go, pkg/utils/sets/doc.go, pkg/utils/sets/generic.go, pkg/utils/sets/generic_test.go, pkg/utils/sets/typed.go
Implements various filter flags for `list` subcommands.
1. Support `--selector` and `--field-selector` flags for all `list` subcommands.
2. Convert `WatchAndPrint` to use generics.
3. Add `pkg/util/sets` package to implement generic version of `k8s.io/apimachinery/pkg/util/sets`.
1. Adds `--states` flag to match Jobs with the given state(s) for `list jobs`.
2. Adds `--running`, `--active` and `--queued` as shorthands for `--states` for `list jobs`.
1. Adds `--scheduled`, `--schedule-enabled` and `--adhoc-only` flags to match JobConfigs with given schedule spec.
=> feat(cli): Implement various filter flags for list subcommands

pkg/cli/cmd/cmd.go, pkg/cli/cmd/cmd_logs.go, pkg/cli/cmd/cmd_logs_test.go, pkg/cli/common/common.go, pkg/utils/testutils/assert.go
Adds a new command `furiko logs`, which fetches and streams logs for a single task (i.e. Pod) in a Job. The Pod must be running.
=> feat(cli): Implement logs command

pkg/cli/cmd/cmd_get_job.go, pkg/cli/cmd/cmd_get_job_test.go, pkg/cli/cmd/cmd_get_jobconfig.go, pkg/cli/cmd/cmd_kill.go, pkg/cli/cmd/cmd_kill_test.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/completion/completer_list_jobconfigs.go, pkg/cli/completion/completer_list_jobs.go, pkg/cli/format/format.go, pkg/cli/format/time.go, pkg/cli/printer/table.go
Rename `github.com/furiko-io/furiko/pkg/cli/formatter` package to `github.com/furiko-io/furiko/pkg/cli/format`, and rename functions to reduce stammering.
=> chore(refactor): Rename formatter -> format

pkg/cli/cmd/cmd_get_job_test.go, pkg/cli/cmd/cmd_get_jobconfig_test.go, pkg/cli/cmd/cmd_list.go, pkg/cli/cmd/cmd_list_job.go, pkg/cli/cmd/cmd_list_job_test.go, pkg/cli/cmd/cmd_list_jobconfig.go, pkg/cli/cmd/cmd_list_jobconfig_test.go, pkg/cli/cmd/cmd_test.go, pkg/cli/common/common.go
Implements `--all-namespaces` (shorthand: `-A`) flag for `furiko list` subcommands.
The behaviour is the same as in `kubectl`:
1. Adds a column `NAMESPACE` at the start of the table when using `-o pretty`
2. Also works when using `--watch`
=> feat(cli): Implement --all-namespaces flag

pkg/cli/cmd/cmd.go, pkg/cli/common/common.go, pkg/cli/common/config.go, pkg/cli/common/flags.go, pkg/cli/completion/completion.go, pkg/cli/completion/kubeconfig_completion.go
1. Fixes the `--kubeconfig` flag which had no effect previously.
2. Introduces `--cluster` and `--context` flags which explicitly specifies the cluster and context to use from the kubeconfig.
3. Implement completion for `--cluster` and `--context`.
=> feat(cli): Fix --kubeconfig and support --cluster and --context flags

.github/workflows/ci.yaml, .golangci.yml, Makefile, pkg/cli/cmd/cmd_disable.go, pkg/cli/cmd/cmd_enable.go, pkg/cli/cmd/cmd_kill.go, pkg/execution/controllers/croncontroller/cron_worker.go, pkg/execution/controllers/croncontroller/util.go, pkg/execution/controllers/jobqueuecontroller/control.go, pkg/execution/taskexecutor/podtaskexecutor/pod_client_test.go, pkg/execution/util/job/condition.go, pkg/execution/util/job/task_test.go, pkg/runtime/httphandler/listener.go, pkg/runtime/httphandler/server.go, pkg/runtime/testing/reconciler.go
Fixes broken lint CI step: https://github.com/furiko-io/furiko/actions/runs/7629655551/job/20783547238
* Bumps `golangci-lint` from v1.45.2 → v1.55.2
* Support versioned `golangci-lint` in `./bin` in case the version is updated
* Remove deprecated linters
* Fix lint errors with stricter linter checks, remove a bunch of unused code
* Add several lint exclusions in case of false positives
=> chore: Bump golangci-lint from v1.45.2 → v1.55.2
